### ISSUE TITLE
[Error] Installation was unsuccessful

### ISSUE THREAD

**Issue by elegabriel** [j0hnnyclaymore/horizon-client-steam-deck#1]
Hi,

I tried both easy and hard solution, but failed with error,
`Extracting VMware Installer...done.`
`[######################################################################] 100%`
`Installation was unsuccessful.`

My current system version is 3.4.4. Have you tried install vmware in steamos recently?

**Comment by elegabriel** [comment]
I removed '--console --required' parameters so that launch the installer with GUI. After select the directory(my /home/deck), I installed VMware horizon successfully.

Maybe the failure is caused by without setting the directory.

After installed successfully, I can reinstall/update vmware horizon with the script given by j0hnnyclaymore. But the .vmware is still at the previously selected directory /home/deck/.vmware, instead of ~/.vmware

**Comment by proxforge** [comment]
@elegabriel  thanks! Yeah I need to test this out with a clean and fresh install. Can you explain "~/.vmware" is "/home/deck/.vmware"

**Comment by elegabriel** [comment]
> 

Yes, it's "/home/deck/.vmware".

**Comment by proxforge** [comment]
Thanks I updated the script to the latest release of the horizon client and changed the parameters. Can you confirm its working now as intendended?
